version: '3.8'
services:
  dev-db:
    image: postgres:${PG_VERSION}
    ports:
      - ${PG_PORTS}
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
